@baseUrl = http://localhost:3333
@authToken = {{authentication.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Usuario Teste",
    "email": "usuariotest@gmail.com",
    "password": "123456"
}

###
# @name authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "usuariotest@gmail.com",
    "password": "123456"
}
###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Pergunta teste3!!",
    "content": "Conteúdo teste"
}

###

# @name fetch_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}